### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by platylm** [SCK-SEAL-TEAM-One/sdet#1]
ตรงหัวข้อ git add อะ อยากให้บอกข้อดีข้อเสียในเรื่องการใช้ git add . กับ git add <path> ด้วยอะ

**Comment by thappatan** [comment]
commit: 2edab948cb82d5b5f0c818f19b7397fe79a0abf0
- [x] เพิ่มข้อดีข้อเสียของการใช้ git add <path> และ git add .
