### ISSUE TITLE
Optimize Docker Images

### ISSUE THREAD

**Issue by platylm** [SCK-SEAL-TEAM-One/sdet#4]
มีคำผิด "ซึ้ง" -> "ซึ่ง" ???

อ่านข้อ 2 "อีกหนึ่งปัญหา คือ การสร้างไม่สร้าง multi-stage ให้กับ dockerFile ซึ่งในการสร้าง multi-stage ให้ Dockerfile นั้นจะช่วยทำให้ขนาดของ image นั้นลดลงอย่างมาก เพราะการทำ multi-stage จะแยกการทำงานระหว่างการ build app และ run app ออกเป็น 2 image จึงทำให้ พอจบ stage ในการ build app แล้ว ก็จะลบ image ในการ build ออกไป ทำให้สามารถลดขนาดที่ไม่จำเป็นในการ run app ออกไป"
แล้วงงๆ อีกหนึ่งปัญหาคือ การสร้างไม่สร้าง ? หมายถึงยังไง, ขนาดของ image นั้นลดลงอย่างมาก เพิ่มตัวอย่างให้เห็นได้ไหมเรื่องลดลง

**Comment by thappatan** [comment]
commit: 22f0908db5a92534ad19dfd1fc5e17da5d735f10
- [x]  Refactor คำผิดจาก "ซึ้ง" -> "ซึ่ง"
- [x]  เพิ่มตัวอย่างรูปภาพการเปรียบเทียบขนาด Docker Image ระหว่างการเขียนแบบ multi-stage และไม่ได้เขียนแบบ multi-stage
